export enum FeatureIdent {
  DEV_MODE = "DEV_MODE",
  WINDOWS_MANAGEMENT = "WINDOWS_MANAGEMENT",
  TABSETS_SHARING = "TABSETS_SHARING",
}

export enum FeatureType {
  RECOMMENDED = "RECOMMENDED",
  OPTIONAL = "OPTIONAL",
  EXPERIMENTAL = "EXPERIMENTAL",
  PLANNED = "PLANNED",
  DISABLED = "DISABLED"
}
