export enum FeatureIdent {
//  OPEN_TABS = "OPEN_TABS",
//  WINDOWS = "WINDOWS",
//  STANDALONE_APP = "STANDALONE_APP",
  WINDOWS_MANAGEMENT = "WINDOWS_MANAGEMENT",
  TABSETS_SHARING = "TABSETS_SHARING",
}

export enum FeatureType {
  RECOMMENDED = "RECOMMENDED",
  OPTIONAL = "OPTIONAL",
  EXPERIMENTAL = "EXPERIMENTAL",
  PLANNED = "PLANNED",
  DISABLED = "DISABLED"
}
