name: Merge from chrome-extension to firefox, edge and opera
on:
  push:
    branches:
      - 'chrome-extension'
jobs:
  sync-branch-firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
#        with:
#          submodules: 'true'

      - name: Merge chrome-extension -> firefox-extension
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: chrome-extension
          target_branch: firefox-extension
          github_token: ${{ secrets.GITHUB_TOKEN }}
